export const CREATE_GAME = "CREATE_GAME";
export const RETRIEVE_GAMES = "RETRIEVE_GAMES";
export const UPDATE_GAME = "UPDATE_GAME";
export const DELETE_GAME = "DELETE_GAME";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const RETRIEVE_ACCOUNT = "RETRIEVE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";